# Generated by Django 3.0.3 on 2020-03-28 21:51

import datetime
from django.db import migrations, models
import django.db.models.manager
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20200329_0158'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blogs',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='blogs',
            name='image',
            field=models.ImageField(default=1, upload_to='posts/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogs',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 28, 21, 51, 53, 864853, tzinfo=utc)),
        ),
    ]
