# Generated by Django 3.0.3 on 2020-03-28 21:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20200329_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 28, 21, 59, 17, 58907, tzinfo=utc)),
        ),
    ]
