# Generated by Django 3.0.3 on 2020-03-31 10:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20200329_0329'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blogs',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='blogs',
            name='read_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogs',
            name='small_title',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogs',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 10, 14, 40, 47034, tzinfo=utc)),
        ),
    ]
