# Generated by Django 3.0.3 on 2020-03-31 11:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20200331_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ('-publish',)},
        ),
        migrations.AlterField(
            model_name='blogs',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 11, 19, 30, 776191, tzinfo=utc)),
        ),
    ]
