# Generated by Django 3.0.3 on 2020-04-01 15:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_auto_20200331_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 15, 21, 44, 544277, tzinfo=utc)),
        ),
    ]
