# Generated by Django 3.0.3 on 2020-04-02 10:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_auto_20200401_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 10, 40, 14, 745401, tzinfo=utc)),
        ),
    ]
