# Generated by Django 3.0.3 on 2020-10-03 06:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0018_auto_20200403_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 6, 59, 32, 994177, tzinfo=utc)),
        ),
    ]
