# Generated by Django 3.0.3 on 2020-10-04 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0019_auto_20201003_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 12, 19, 10, 649017)),
        ),
    ]
